force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Factor1__c.field-meta.xml
<CustomField>
    <fullName>Factor1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Factor2__c.field-meta.xml
<CustomField>
    <fullName>Factor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Factor3__c.field-meta.xml
<CustomField>
    <fullName>Factor3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Factor4__c.field-meta.xml
<CustomField>
    <fullName>Factor4__c</fullName>
    <label>Factor4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Factor5__c.field-meta.xml
<CustomField>
    <fullName>Factor5__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Factor6__c.field-meta.xml
<CustomField>
    <fullName>Factor6__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Priority</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <label>Scenario</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario__c/fields/Factor1__c.field-meta.xml
<CustomField>
    <fullName>Factor1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Factor2__c.field-meta.xml
<CustomField>
    <fullName>Factor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Factor3__c.field-meta.xml
<CustomField>
    <fullName>Factor3__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Factor4__c.field-meta.xml
<CustomField>
    <fullName>Factor4__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Factor5__c.field-meta.xml
<CustomField>
    <fullName>Factor5__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Factor6__c.field-meta.xml
<CustomField>
    <fullName>Factor6__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Factor6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applied Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Scenarios</relationshipLabel>
    <relationshipName>Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RuleApplyingCheckTest.cls
@isTest
private class RuleApplyingCheckTest {
  @testSetup
  public static void createData() {
    List<Scenario__c> scenarios = new List<Scenario__c>();
    List<ScenarioCombinationGenerate.FlowInputParameters> inputList = new List<ScenarioCombinationGenerate.FlowInputParameters>();
    ScenarioCombinationGenerate.FlowInputParameters input = new ScenarioCombinationGenerate.FlowInputParameters();
    input.name = 'Test';
    input.factor1 = new List<String>{ 'A', 'B', 'C' };
    input.factor2 = new List<String>{ 'a2', 'b2', 'c2' };
    input.factor3 = new List<String>{ 'A3', 'B3', 'C3' };
    input.factor4 = new List<String>{ 'A4', 'B4', 'C4' };
    input.factor5 = new List<String>{ 'A5', 'B5', 'C5' };
    input.factor6 = new List<String>{ 'A6', 'B6', 'C6' };
    inputList.add(input);
    List<ScenarioCombinationGenerate.FlowOutputParameters> result = ScenarioCombinationGenerate.createPermutations(
      inputList
    );
    for (ScenarioCombinationGenerate.FlowOutputParameters output : result) {
      scenarios.addAll(output.records);
    }
    insert scenarios;
    // List<Rule__c> rules = new List<Rule__c>();
    // Rule__c rule1 = new Rule__c(Name = 'Rule - 1', factor1 = 'A', factor2 = 'b2', order__c = 1);
    // Rule__c rule2 = new Rule__c(Name = 'Rule - 2', factor1 = 'A', factor2 = 'b2', order__c = 2);
    // Rule__c rule3 = new Rule__c(Name = 'Rule - 3', factor1 = 'A', factor2 = 'b2', order__c = 3);
    // rules.add(rule1);
    // rules.add(rule2);
    // rules.add(rule3);
    // insert rules;
  }
  @isTest
  public static void testRule1() {
    List<RuleApplyingCheck.FlowInputParameters> inputList = new List<RuleApplyingCheck.FlowInputParameters>();
    RuleApplyingCheck.FlowInputParameters input = new RuleApplyingCheck.FlowInputParameters();
    Rule__c rule1 = new Rule__c(
      Name = 'Rule - 1',
      factor1__c = 'A',
      factor2__c = 'b2'
    );
    insert rule1;
    input.rule = rule1;
    input.scenarios = [
      SELECT
        Name,
        Factor1__c,
        Factor2__c,
        Factor3__c,
        Factor4__c,
        Factor5__c,
        Factor6__c,
        Rule__c
      FROM Scenario__c
    ];
    inputList.add(input);
    test.startTest();
    List<RuleApplyingCheck.FlowOutputParameters> result = RuleApplyingCheck.checkRule(
      inputList
    );
    for (RuleApplyingCheck.FlowOutputParameters output : result) {
      System.assertEquals(81, output.records.size(), 'Number not matching');
    }
  }
}