force-app/main/default/objects/ElementData__c/ElementData__c.object-meta.xml
<CustomObject>
    <label>Element Data</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementData__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Variable ID</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/ElementData1__c.field-meta.xml
<CustomField>
    <fullName>ElementData1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element Data 1</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Rule 1</relationshipLabel>
    <relationshipName>Rules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/ElementData2__c.field-meta.xml
<CustomField>
    <fullName>ElementData2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element Data 2</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Rule 2</relationshipLabel>
    <relationshipName>Rules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/ElementData3__c.field-meta.xml
<CustomField>
    <fullName>ElementData3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element Data 3</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Rule 3</relationshipLabel>
    <relationshipName>Rules3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Priority</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <label>Scenario</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario__c/fields/ElementData1__c.field-meta.xml
<CustomField>
    <fullName>ElementData1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variable 1</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Scenario 1</relationshipLabel>
    <relationshipName>Scenarios1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/ElementData2__c.field-meta.xml
<CustomField>
    <fullName>ElementData2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variable 2</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Scenario 2</relationshipLabel>
    <relationshipName>Scenarios2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/ElementData3__c.field-meta.xml
<CustomField>
    <fullName>ElementData3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Element Data 3</label>
    <referenceTo>ElementData__c</referenceTo>
    <relationshipLabel>Element Scenario 3</relationshipLabel>
    <relationshipName>Scenarios3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applied Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Scenarios</relationshipLabel>
    <relationshipName>Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RulesToScenariosCheckTest.cls
@isTest
private class RulesToScenariosCheckTest {
  @testSetup
  public static void createData() {
    List<ElementData__c> data = new List<ElementData__c>();
    for (Integer i = 1; i < 7; i++) {
      ElementData__c element1 = new ElementData__c();
      element1.Name = 'Test';
      element1.Order__c = i;
      element1.Value__c = 'A1 ' + i;
      data.add(element1);
      ElementData__c element2 = new ElementData__c();
      element2.Name = 'Test';
      element2.Order__c = i;
      element2.Value__c = 'B1 ' + i;
      data.add(element2);
    }
    insert data;

    List<ScenarioFromElementsCreate.FlowInputParameters> inputList = new List<ScenarioFromElementsCreate.FlowInputParameters>();
    ScenarioFromElementsCreate.FlowInputParameters input = new ScenarioFromElementsCreate.FlowInputParameters();
    List<Scenario__c> scenarios = new List<Scenario__c>();
    input.elementName = 'Test';
    // input.maxOrder = 6;
    inputList.add(input);
    List<ScenarioFromElementsCreate.FlowOutputParameters> result = ScenarioFromElementsCreate.createPermutations(
      inputList
    );
    for (ScenarioFromElementsCreate.FlowOutputParameters output : result) {
      scenarios.addAll(output.records);
    }
    insert scenarios;
  }

  @isTest
  public static void testRule() {
    List<RulesToScenariosCheck.FlowInputParameters> inputList = new List<RulesToScenariosCheck.FlowInputParameters>();
    RulesToScenariosCheck.FlowInputParameters input = new RulesToScenariosCheck.FlowInputParameters();
    ElementData__c element1 = [
      SELECT Id
      FROM ElementData__c
      WHERE order__c = 1
    ][0];
    ElementData__c element2 = [
      SELECT Id
      FROM ElementData__c
      WHERE order__c = 2
    ][0];
    ElementData__c element3 = [
      SELECT Id
      FROM ElementData__c
      WHERE order__c = 3
    ][0];
    Rule__c rule1 = new Rule__c(
      Name = 'Rule - 1',
      ElementData1__c = element1.Id,
      ElementData2__c = element2.Id,
      Order__c = 1
    );
    Rule__c rule2 = new Rule__c(
      Name = 'Rule - 2',
      ElementData1__c = element1.Id,
      ElementData3__c = element3.Id,
      Order__c = 2
    );
    insert rule1;
    insert rule2;
    input.rule = 'Rule';
    input.scenario = 'Test';
    inputList.add(input);
    test.startTest();
    List<RulesToScenariosCheck.FlowOutputParameters> result = RulesToScenariosCheck.applyRules(
      inputList
    );
    for (RulesToScenariosCheck.FlowOutputParameters output : result) {
      System.assertEquals(24, output.records.size(), 'Number not matching');
    }
  }
}