force-app/main/default/objects/ElementData__c/ElementData__c.object-meta.xml
<CustomObject>
    <label>Element Data</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementData__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Variable ID</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <label>Scenario</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScenarioFromElementsCreateTest.cls
@isTest
private class ScenarioFromElementsCreateTest {
  @testSetup
  public static void createData() {
    List<ElementData__c> data = new List<ElementData__c>();
    for (Integer i = 1; i < 7; i++) {
      ElementData__c element1 = new ElementData__c();
      element1.Name = 'Test';
      element1.Order__c = i;
      element1.Value__c = 'A1 ' + i;
      data.add(element1);
      ElementData__c element2 = new ElementData__c();
      element2.Name = 'Test';
      element2.Order__c = i;
      element2.Value__c = 'B1 ' + i;
      data.add(element2);
    }
    insert data;
  }
  @isTest
  public static void testCreate() {
    List<ScenarioFromElementsCreate.FlowInputParameters> inputList = new List<ScenarioFromElementsCreate.FlowInputParameters>();
    ScenarioFromElementsCreate.FlowInputParameters input = new ScenarioFromElementsCreate.FlowInputParameters();
    List<Scenario__c> scenarios = new List<Scenario__c>();
    input.elementName = 'Test';
    // input.maxOrder = 6;
    inputList.add(input);
    List<ScenarioFromElementsCreate.FlowOutputParameters> result = ScenarioFromElementsCreate.createPermutations(
      inputList
    );
    for (ScenarioFromElementsCreate.FlowOutputParameters output : result) {
      scenarios.addAll(output.records);
    }
    List<ElementData__c> data = [SELECT Id FROM ElementData__c];
    System.assertEquals(64, scenarios.size(), 'Number not matching');
  }
}